print("|{:-^50}|".format(""))
print("|{:^50}|".format("Welcome"))
print("|{:-^50}|".format(""))
print("|{:^50}|".format("Choose one operation: "))
print("|{:50}|".format("  1. Signup"))
print("|{:50}|".format("  2. Signin"))
print("|{:50}|".format("  3. Admin Signin"))
print("|{:50}|".format("  4. Quit"))
print("|{:-^50}|".format(""))
print("|{:50}|".format("Enter your choice: "))